plugins {
    id 'java'
    id 'application'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.glazedlists:glazedlists:1.11.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.25.2'
    implementation 'org.apache.logging.log4j:log4j-api:2.25.2'
    annotationProcessor 'org.apache.logging.log4j:log4j-core:2.25.2'
    implementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.25.2'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.20.1'
    implementation 'com.google.guava:guava:33.6.0-jre'
    implementation project(':FF4StatsLib')

    testImplementation 'junit:junit:4.13.2'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '-Xlint:unchecked'
    options.compilerArgs << '-Xlint:deprecation'
}

application {
    mainClass = 'sg4e.maikatracker.MaikaTracker'
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
            'Main-Class': application.mainClass.get(),
            'Multi-Release': 'true'
        )
    }

    from(project(':FF4StatsLib').sourceSets.main.output)

    from {
        configurations.runtimeClasspath
            .findAll { it.exists() && !it.path.contains('/FF4StatsLib/build/libs/') }
            .collect { it.isDirectory() ? it : zipTree(it) }
    }
}
